{
  "formatVersion": "1.1",
  "component": {
    "group": "com.stay22",
    "module": "sdk",
    "version": "1.0.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-1.0.10.aar",
          "url": "sdk-1.0.10.aar",
          "size": 155479,
          "sha512": "8c93d5418746903f0a589899da667f055fcbfaa41804b0030ed930d4d67520fd68fe75e43eb2363c0b38ae4e8cd4766b5d2d902ec95775aca998ca76a04d0b27",
          "sha256": "47ed533ac9c87a563f710b9d296f5a1f166d8779bed22a3f9c04218054395fa4",
          "sha1": "744dcb4c1a9e276cb37111ff7787cc9ecedd8c7e",
          "md5": "9fdf518d7969b209492c4a91be1cd793"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-1.0.10.aar",
          "url": "sdk-1.0.10.aar",
          "size": 155479,
          "sha512": "8c93d5418746903f0a589899da667f055fcbfaa41804b0030ed930d4d67520fd68fe75e43eb2363c0b38ae4e8cd4766b5d2d902ec95775aca998ca76a04d0b27",
          "sha256": "47ed533ac9c87a563f710b9d296f5a1f166d8779bed22a3f9c04218054395fa4",
          "sha1": "744dcb4c1a9e276cb37111ff7787cc9ecedd8c7e",
          "md5": "9fdf518d7969b209492c4a91be1cd793"
        }
      ]
    }
  ]
}
