{
  "formatVersion": "1.1",
  "component": {
    "group": "com.stay22",
    "module": "sdk",
    "version": "1.0.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-1.0.12.aar",
          "url": "sdk-1.0.12.aar",
          "size": 155686,
          "sha512": "52c6b0bba3773defb0d8e15aeda3338138228bd8110c7fabbd071f3f99415fb01a61b91b793896844e84396fbda388f0bcd944c677a5b3fa59d3c0b98aaedbf8",
          "sha256": "0114dfd63514b7c731fcba29d2723e50079317b1860bd0752dd1ee5fdc00db5a",
          "sha1": "ed149feccdab2ac240046a5848931e19b0a6c94a",
          "md5": "3f7e99655dfbf28a90309995afc7497e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-1.0.12.aar",
          "url": "sdk-1.0.12.aar",
          "size": 155686,
          "sha512": "52c6b0bba3773defb0d8e15aeda3338138228bd8110c7fabbd071f3f99415fb01a61b91b793896844e84396fbda388f0bcd944c677a5b3fa59d3c0b98aaedbf8",
          "sha256": "0114dfd63514b7c731fcba29d2723e50079317b1860bd0752dd1ee5fdc00db5a",
          "sha1": "ed149feccdab2ac240046a5848931e19b0a6c94a",
          "md5": "3f7e99655dfbf28a90309995afc7497e"
        }
      ]
    }
  ]
}
