{
  "formatVersion": "1.1",
  "component": {
    "group": "com.stay22",
    "module": "sdk",
    "version": "1.0.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-1.0.11.aar",
          "url": "sdk-1.0.11.aar",
          "size": 155476,
          "sha512": "219e0e0cec52d763f742f5e3e9a0c77b9c4460816711fe66e62bd81c191b6e3a9aa818ba08112d087a9b7f178cf39d45bc3bf5d713b987be496b621d20498cfe",
          "sha256": "91c9e0f6ea9a061c6a50227da907aedc5574ed838b02ceccce04be8bd4f8d105",
          "sha1": "2806b0e5d6db81a8840cc7dd0c3201dc2e41cc22",
          "md5": "b40d6d419ee208ade1558b9b4fdfe942"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-1.0.11.aar",
          "url": "sdk-1.0.11.aar",
          "size": 155476,
          "sha512": "219e0e0cec52d763f742f5e3e9a0c77b9c4460816711fe66e62bd81c191b6e3a9aa818ba08112d087a9b7f178cf39d45bc3bf5d713b987be496b621d20498cfe",
          "sha256": "91c9e0f6ea9a061c6a50227da907aedc5574ed838b02ceccce04be8bd4f8d105",
          "sha1": "2806b0e5d6db81a8840cc7dd0c3201dc2e41cc22",
          "md5": "b40d6d419ee208ade1558b9b4fdfe942"
        }
      ]
    }
  ]
}
