{
  "formatVersion": "1.1",
  "component": {
    "group": "com.stay22",
    "module": "sdk",
    "version": "1.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-1.0.9.aar",
          "url": "sdk-1.0.9.aar",
          "size": 158254,
          "sha512": "72224b5df97d1b3ebddfed1ca1e0701c597f5b8bdf01c057b3e818969825c213f44e7542cc9daab184b6448d27574769167a011a2c76aa2f7354d3a72354707d",
          "sha256": "dc05cd1f4b17defc7ccd7c76cf3dd0983441d9f7b19fc951787ea69eb761eb73",
          "sha1": "de9f692ac0611ae0268b6d84038d82b363af6e19",
          "md5": "82efb09d2664fd5f88b9f3e676ccd252"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-1.0.9.aar",
          "url": "sdk-1.0.9.aar",
          "size": 158254,
          "sha512": "72224b5df97d1b3ebddfed1ca1e0701c597f5b8bdf01c057b3e818969825c213f44e7542cc9daab184b6448d27574769167a011a2c76aa2f7354d3a72354707d",
          "sha256": "dc05cd1f4b17defc7ccd7c76cf3dd0983441d9f7b19fc951787ea69eb761eb73",
          "sha1": "de9f692ac0611ae0268b6d84038d82b363af6e19",
          "md5": "82efb09d2664fd5f88b9f3e676ccd252"
        }
      ]
    }
  ]
}
