{
  "formatVersion": "1.1",
  "component": {
    "group": "com.stay22",
    "module": "sdk",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-1.2.0.aar",
          "url": "sdk-1.2.0.aar",
          "size": 184189,
          "sha512": "75bdcc9fada119d1be7ae80516d6304909a98161cdbac8396c872f54d9ed205b0e88340f59a8a9fb14aa8ac4c97939f8ad5c6468583e3792a293b14734d85e95",
          "sha256": "d2e758d7be86025ac24ee05adac3dbe487a8262b7b3c27313e7cf712563f1b4c",
          "sha1": "4af4cb2ecda04a865c215961735c99b0e35f3fe9",
          "md5": "bb067e364276dd3de6a22e64435643bb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-1.2.0.aar",
          "url": "sdk-1.2.0.aar",
          "size": 184189,
          "sha512": "75bdcc9fada119d1be7ae80516d6304909a98161cdbac8396c872f54d9ed205b0e88340f59a8a9fb14aa8ac4c97939f8ad5c6468583e3792a293b14734d85e95",
          "sha256": "d2e758d7be86025ac24ee05adac3dbe487a8262b7b3c27313e7cf712563f1b4c",
          "sha1": "4af4cb2ecda04a865c215961735c99b0e35f3fe9",
          "md5": "bb067e364276dd3de6a22e64435643bb"
        }
      ]
    }
  ]
}
