{
  "formatVersion": "1.1",
  "component": {
    "group": "com.stay22",
    "module": "sdk",
    "version": "1.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-1.4.0.aar",
          "url": "sdk-1.4.0.aar",
          "size": 208897,
          "sha512": "3edb4ff06258cfca24333be0dd2ed55cfc6d8667eb8e9ae9daa7d5d11fcbd77d1845c01a2e97e8bab05381072e4d599f332b8fcd628e1f8893e0b813596395f5",
          "sha256": "37bda946b8f6476bb3d061fee5f793a23f69fd65309d3a43b6a28bf25ddd7e91",
          "sha1": "b5f0683f5e32d041d6e60e1fb2652a31121b1a7c",
          "md5": "0586b7bf43c39f957abf85dda4f04e59"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-1.4.0.aar",
          "url": "sdk-1.4.0.aar",
          "size": 208897,
          "sha512": "3edb4ff06258cfca24333be0dd2ed55cfc6d8667eb8e9ae9daa7d5d11fcbd77d1845c01a2e97e8bab05381072e4d599f332b8fcd628e1f8893e0b813596395f5",
          "sha256": "37bda946b8f6476bb3d061fee5f793a23f69fd65309d3a43b6a28bf25ddd7e91",
          "sha1": "b5f0683f5e32d041d6e60e1fb2652a31121b1a7c",
          "md5": "0586b7bf43c39f957abf85dda4f04e59"
        }
      ]
    }
  ]
}
