{
  "formatVersion": "1.1",
  "component": {
    "group": "com.stay22",
    "module": "sdk",
    "version": "1.6.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-1.6.2.aar",
          "url": "sdk-1.6.2.aar",
          "size": 256505,
          "sha512": "1f5b908a5699a2b6c8e4971515891fc3251dea5afc9860a8d2d021c4467a4677f0542413dbbb3368f230e477dd673b757721dc27645743037b5e34a90c5756ed",
          "sha256": "7ae17601484630c51d4cc32c8179bc4ce5cf7108d05aa4a69692bc5c9e91b19d",
          "sha1": "bd37bd240f2d1a5d0a7ba488bb2c422123890aa7",
          "md5": "dbe814aaf014293062f3538936aa9615"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-1.6.2.aar",
          "url": "sdk-1.6.2.aar",
          "size": 256505,
          "sha512": "1f5b908a5699a2b6c8e4971515891fc3251dea5afc9860a8d2d021c4467a4677f0542413dbbb3368f230e477dd673b757721dc27645743037b5e34a90c5756ed",
          "sha256": "7ae17601484630c51d4cc32c8179bc4ce5cf7108d05aa4a69692bc5c9e91b19d",
          "sha1": "bd37bd240f2d1a5d0a7ba488bb2c422123890aa7",
          "md5": "dbe814aaf014293062f3538936aa9615"
        }
      ]
    }
  ]
}
