{
  "formatVersion": "1.1",
  "component": {
    "group": "com.stay22",
    "module": "sdk",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-1.3.0.aar",
          "url": "sdk-1.3.0.aar",
          "size": 185392,
          "sha512": "62f15aa4930e91b58e955f7f44e78e75414074a813fc6fa8a245128a5c3d82dbd3aa76b57c9ba7fba6c720b3d77fa4b787d30ae99064f1021366691cde81e023",
          "sha256": "f3f275346198129a9b783735a8d394bfb6403232889c83333f8432ef1a7a952f",
          "sha1": "17ec5503a5d83d81c711c17cd5496ea3effdc2bd",
          "md5": "e6da5cf8dd1d16f657b8b8596fd6706f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-1.3.0.aar",
          "url": "sdk-1.3.0.aar",
          "size": 185392,
          "sha512": "62f15aa4930e91b58e955f7f44e78e75414074a813fc6fa8a245128a5c3d82dbd3aa76b57c9ba7fba6c720b3d77fa4b787d30ae99064f1021366691cde81e023",
          "sha256": "f3f275346198129a9b783735a8d394bfb6403232889c83333f8432ef1a7a952f",
          "sha1": "17ec5503a5d83d81c711c17cd5496ea3effdc2bd",
          "md5": "e6da5cf8dd1d16f657b8b8596fd6706f"
        }
      ]
    }
  ]
}
