{
  "formatVersion": "1.1",
  "component": {
    "group": "com.stay22",
    "module": "sdk",
    "version": "1.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-1.0.8.aar",
          "url": "sdk-1.0.8.aar",
          "size": 158248,
          "sha512": "3a05716d2742d1db1c073739c77784f9924e9d67666c0978bef29d8a283433bbb0b76e0cfb8fcfe5504e97c21440026286c62a80ef1bdc4eac012a01156b85fc",
          "sha256": "fa315603ad32d7c62463898d755ecebdb8bf6d1c50d5f4c0a69d47e0c85cb304",
          "sha1": "74ed75353f8763f519462948f381245ceebec460",
          "md5": "a40d64930cce2e49f77fc246e3ad69ec"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-1.0.8.aar",
          "url": "sdk-1.0.8.aar",
          "size": 158248,
          "sha512": "3a05716d2742d1db1c073739c77784f9924e9d67666c0978bef29d8a283433bbb0b76e0cfb8fcfe5504e97c21440026286c62a80ef1bdc4eac012a01156b85fc",
          "sha256": "fa315603ad32d7c62463898d755ecebdb8bf6d1c50d5f4c0a69d47e0c85cb304",
          "sha1": "74ed75353f8763f519462948f381245ceebec460",
          "md5": "a40d64930cce2e49f77fc246e3ad69ec"
        }
      ]
    }
  ]
}
